- name: Install extension
  ansible.builtin.include_role:
    name: jaredhocutt.gnome_extensions
  vars:
    gnome_extension_ids:
      - 4269

- name: "Set '[...] app-grid folder-order-position' to end"
  gsetting:
    schema: org.gnome.shell.extensions.alphabetical-app-grid
    key: folder-order-position
    value: "end"
