- name: Install extension
  ansible.builtin.include_role:
    name: jaredhocutt.gnome_extensions
  vars:
    gnome_extension_ids:
      - 3193

- name: "Set '[...] appfolder blur' to false"
  gsetting:
    schema: org.gnome.shell.extensions.blur-my-shell.appfolder
    key: blur
    value: "false"

- name: "Set '[...] lockscreen blur' to false"
  gsetting:
    schema: org.gnome.shell.extensions.blur-my-shell.lockscreen
    key: blur
    value: "false"

- name: "Set '[...] screenshot blur' to false"
  gsetting:
    schema: org.gnome.shell.extensions.blur-my-shell.screenshot
    key: blur
    value: "false"

- name: "Set '[...] window-list blur' to false"
  gsetting:
    schema: org.gnome.shell.extensions.blur-my-shell.window-list
    key: blur
    value: "false"

- name: "Set '[...] panel blur' to false"
  gsetting:
    schema: org.gnome.shell.extensions.blur-my-shell.panel
    key: blur
    value: "false"

- name: "Set '[...] overview blur' to true"
  gsetting:
    schema: org.gnome.shell.extensions.blur-my-shell.overview
    key: blur
    value: "true"

- name: "Set '[...] overview pipeline' to pipeline_default"
  gsetting:
    schema: org.gnome.shell.extensions.blur-my-shell.overview
    key: pipeline
    value: "pipeline_default"

- name: "Set '[...] panel blur' to false"
  gsetting:
    schema: org.gnome.shell.extensions.blur-my-shell.panel
    key: blur
    value: "false"

- name: "Set '[...] dash-to-dock blur' to true"
  gsetting:
    schema: org.gnome.shell.extensions.blur-my-shell.dash-to-dock
    key: blur
    value: "true"

- name: "Set '[...] dash-to-dock brightness' to 0.6"
  gsetting:
    schema: org.gnome.shell.extensions.blur-my-shell.dash-to-dock
    key: brightness
    value: "0.6"

- name: "Set '[...] dash-to-dock sigma' to 30"
  gsetting:
    schema: org.gnome.shell.extensions.blur-my-shell.dash-to-dock
    key: sigma
    value: "30"

- name: "Set '[...] dash-to-dock static-blur' to true"
  gsetting:
    schema: org.gnome.shell.extensions.blur-my-shell.dash-to-dock
    key: static-blur
    value: "true"

- name: "Set '[...] dash-to-dock style-dash-to-dock' to 0"
  gsetting:
    schema: org.gnome.shell.extensions.blur-my-shell.dash-to-dock
    key: style-dash-to-dock
    value: "0"
