- name: Install extension
  ansible.builtin.include_role:
    name: jaredhocutt.gnome_extensions
  vars:
    gnome_extension_ids:
      - 5090

- name: "Set 'smart-workspace-names' to false"
  gsetting:
    schema: org.gnome.shell.extensions.space-bar.behavior
    key: smart-workspace-names
    value: "false"

- name: "Set 'enable-activate-workspace-shortcuts' to false"
  gsetting:
    schema: org.gnome.shell.extensions.space-bar.shortcuts
    key: enable-activate-workspace-shortcuts
    value: "false"

- name: "Set 'enable-move-to-workspace-shortcuts' to true"
  gsetting:
    schema: org.gnome.shell.extensions.space-bar.shortcuts
    key: enable-move-to-workspace-shortcuts
    value: "true"

- name: "Set 'open-menu' to @as []"
  gsetting:
    schema: org.gnome.shell.extensions.space-bar.shortcuts
    key: open-menu
    value: "@as []"
