- name: Install extension
  ansible.builtin.include_role:
    name: jaredhocutt.gnome_extensions
  vars:
    gnome_extension_ids:
      - 4548

- name: "Set 'col-0' to 1"
  gsetting:
    schema: org.gnome.shell.extensions.tactile
    key: col-0
    value: 1

- name: "Set 'col-1' to 2"
  gsetting:
    schema: org.gnome.shell.extensions.tactile
    key: col-1
    value: 2

- name: "Set 'col-2' to 1"
  gsetting:
    schema: org.gnome.shell.extensions.tactile
    key: col-2
    value: 1

- name: "Set 'col-3' to 0"
  gsetting:
    schema: org.gnome.shell.extensions.tactile
    key: col-3
    value: 0

- name: "Set 'row-0' to 1"
  gsetting:
    schema: org.gnome.shell.extensions.tactile
    key: row-0
    value: 1

- name: "Set 'row-1' to 1"
  gsetting:
    schema: org.gnome.shell.extensions.tactile
    key: row-1
    value: 1

- name: "Set 'gap-size' to 32"
  gsetting:
    schema: org.gnome.shell.extensions.tactile
    key: gap-size
    value: 32
