---
- name: Install packages from RPM, Flathub and other sources
  hosts: localhost
  become: true
  tasks:
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Import 1Password RPM key
      ansible.builtin.rpm_key:
        state: present
        key: https://downloads.1password.com/linux/keys/1password.asc

    - name: Add 1Password YUM repository
      ansible.builtin.yum_repository:
        name: 1password
        description: 1Password Stable Channel
        baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: https://downloads.1password.com/linux/keys/1password.asc

    - name: Enable COPR project for Iosevka font
      community.general.copr:
        name: peterwu/iosevka

    - name: Enable COPR project for lazygit
      community.general.copr:
        name: atim/lazygit

    - name: Install RPM packages
      ansible.builtin.dnf:
        name:
          - 1password
          - alacritty
          - delve
          - fastfetch
          - go
          - iosevka-term-fonts
          - lazygit
          - neovim
          - ripgrep
          - shellcheck
          - shfmt
          - tmux
          - zathura
        state: present

    - name: Install Flatpak packages
      community.general.flatpak:
        name:
          - com.spotify.Client
          - com.synology.SynologyDrive
          - org.localsend.localsend_app
          - org.zotero.Zotero
          - us.zoom.Zoom
          - md.obsidian.Obsidian
        state: present
