- name: Add the flathub flatpak repository remote to the user installation
  become: true
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Import 1Password RPM key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://downloads.1password.com/linux/keys/1password.asc

- name: Add 1Password YUM repository
  become: true
  ansible.builtin.yum_repository:
    name: 1password
    description: 1Password Stable Channel
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc

- name: Enable COPR project for Iosevka font
  become: true
  community.general.copr:
    name: peterwu/iosevka

- name: Enable COPR project for lazygit
  become: true
  community.general.copr:
    name: atim/lazygit

- name: Install RPM packages
  become: true
  ansible.builtin.dnf:
    name:
      - 1password
      - 1password-cli
      - alacritty
      - delve
      - fastfetch
      - go
      - iosevka-term-fonts
      - lazygit
      - neovim
      - pipx
      - ripgrep
      - shellcheck
      - shfmt
      - sushi
      - tmux
      - zathura
    state: present

- name: Install Flatpak packages
  become: true
  community.general.flatpak:
    name:
      - com.spotify.Client
      - com.synology.SynologyDrive
      - org.localsend.localsend_app
      - org.zotero.Zotero
      - us.zoom.Zoom
      - md.obsidian.Obsidian
    state: present
