- name: Define the list of favorite apps
  ansible.builtin.set_fact:
    apps:
      - "1password.desktop"
      - "Activity.desktop"
      - "Alacritty.desktop"
      - "Docker.desktop"
      - "Neovim.desktop"
      - "com.spotify.Client.desktop"
      - "md.obsidian.Obsidian.desktop"
      - "org.gnome.Nautilus.desktop"
      - "org.gnome.Settings.desktop"
      - "org.localsend.localsend_app.desktop"
      - "org.mozilla.firefox.desktop"
      - "us.zoom.Zoom.desktop"

- name: Define directories where .desktop files are stored
  ansible.builtin.set_fact:
    desktop_dirs:
      - "/var/lib/flatpak/exports/share/applications"
      - "/usr/share/applications"
      - "/usr/local/share/applications"
      - "{{ ansible_env.HOME }}/.local/share/applications"

- name: Initialize an empty list for installed apps
  ansible.builtin.set_fact:
    installed_apps: []

- name: Check if each app is installed
  ansible.builtin.set_fact:
    installed_apps: "{{ installed_apps + [item[0]] }}"
  when: "item[0] in lookup('ansible.builtin.fileglob', item[1] + '/*.desktop')"
  loop: "{{ apps | product(desktop_dirs) }}"

- name: Format the list for gsettings
  ansible.builtin.set_fact:
    favorites_list: "[ {{ installed_apps | map('to_json') | join(',') }} ]"

- name: "Set 'favorite-apps' to {{ favorites_list }}"
  gsetting:
    schema: org.gnome.shell
    key: favorite-apps
    value: "{{ favorites_list }}"
